name: Tests & Allure Pages

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write          # required for Pages
  id-token: write       # required for Pages

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-and-build-allure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run tests
        run: mvn -B clean test

      # Creates static HTML at target/site/allure-maven-plugin
      - name: Generate Allure report
        run: mvn -B -DskipTests -Dallure.results.directory=target/allure-results allure:report

      # Upload the HTML folder as the Pages artifact
      - name: Upload Allure site for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/allure-maven-plugin

  deploy:
    needs: test-and-build-allure
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
